name: Tracy Startup Profiling
on:
  push:

jobs:
  run_tracy_profiling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore BYOND cache
        uses: actions/cache@v3
        with:
          path: ~/BYOND
          key: ${{ runner.os }}-byond-${{ secrets.CACHE_PURGE_KEY }}

      - name: Install rust-g
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update || true
          sudo apt install -o APT::Immediate-Configure=false zlib1g-dev:i386 libssl-dev:i386
          bash tools/ci/install_rust_g.sh

      - name: Build Tracy tools
        env:
          TRACY_VERSION: "0.11.1"
        run: |
          sudo apt-get install -y cmake libtbb-dev libdbus-1-dev
          git clone --depth 1 --branch v${TRACY_VERSION} https://github.com/wolfpld/tracy.git tracy-src
          cmake -S tracy-src/capture  -B tracy-src/capture/build  -DCMAKE_BUILD_TYPE=Release
          cmake --build tracy-src/capture/build  --parallel
          cmake -S tracy-src/csvexport -B tracy-src/csvexport/build -DCMAKE_BUILD_TYPE=Release
          cmake --build tracy-src/csvexport/build --parallel
          cp tracy-src/capture/build/tracy-capture   ./tracy-capture
          cp tracy-src/csvexport/build/tracy-csvexport ./tracy-csvexport

      - name: Install byond-tracy
        run: |
          wget -q "https://github.com/spacestation13/byond-tracy/releases/latest/download/libprof.so"

      - name: Compile for profiling
        run: |
          bash tools/ci/install_byond.sh
          source $HOME/BYOND/byond/bin/byondsetup
          tools/build/build.sh -DTRACY_PROFILE_AND_EXIT -Werror

      - name: Run profiling capture
        run: |
          source $HOME/BYOND/byond/bin/byondsetup
          cd $GITHUB_WORKSPACE
          bash tools/ci/profile_startup.sh startup.csv

      - name: Upload Tracy capture
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tracy-profile
          path: |
            startup.csv
            startup.tracy
